# Generated by Django 5.2.6 on 2025-09-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationProfile',
            new_name='ApplicantProfile',
        ),
    ]
