# Generated by Django 5.2.6 on 2025-09-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_applicationprofile_applicantprofile_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recruiterprofile',
            index=models.Index(fields=['company_name'], name='users_recru_company_914aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiterprofile',
            index=models.Index(fields=['position'], name='users_recru_positio_22b5f9_idx'),
        ),
    ]
