# Generated by Django 5.2.6 on 2025-09-21 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('jobs', '0003_jobposting_jobs_jobpos_title_afd3ed_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobapplications',
            index=models.Index(fields=['job', 'applicant'], name='application_job_id_edef16_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplications',
            index=models.Index(fields=['status'], name='application_status_6f6b30_idx'),
        ),
    ]
