# Generated by Django 5.2.6 on 2025-09-21 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['title'], name='jobs_jobpos_title_afd3ed_idx'),
        ),
    ]
