# Generated by Django 5.2.6 on 2025-09-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobposting_jobs_jobpos_title_afd3ed_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On-site')], default='onsite', max_length=10),
        ),
    ]
